version: '3.8'

services:
  app:
    image: devi-revolutti:0.1.0
    build: ./app
    environment:
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASS: "${DATABASE_PASS}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "mysql"
    ports:
      - "8000:8000"
    networks:
      - devi-revolutti

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASS}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASS}'
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - devi-revolutti

networks:
  devi-revolutti:
    driver: bridge
