# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ghcr.io/s3lcsum/devi-revolutti
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: "github-registry"

serviceAccount:
  # Specifies whether a service account should be created
  create: true

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

env:
  # In default environment value of DATABASE_HOST will be pointing to database service
  # which has been deployed in another chart (mysql)
  DATABASE_HOST: "database-mysql-primary"
  DATABASE_USER: "devi"
  DATABASE_PASS: "3cNs8KqVDIwORRYQ0B"