name: Build image

on:
  push:

concurrency: ci-${{ github.sha }}

env:
  DOCKER_IMAGE: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        working-directory: app
        run: |
          make build TAG=ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Publish image to Github Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}